name: Edge AI Gateway
slug: edge_ai_gateway
version: "2.0.16"
description: Edge AI decision service
arch:
  - aarch64
  - armv7
  - amd64
startup: services
boot: auto
host_network: true
map:
  - share:rw
options: {}
schema: {}